### 1. 数据预处理

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

## 读取数据信息
data = pd.read_csv("D:/cao/kaggle/Titanic/data/train.csv")
data.info()
data.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
# 将 sex 特征转换为类别数据
data['Sex'] = data['Sex'].apply(lambda s:1 if s == 'male' else 0)
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# 将所有缺失的字段填充为0,取部分特征用于训练
data = data.fillna(0)
dataset_X = data[['Sex', 'Age', 'Pclass', 'SibSp', 'Parch', 'Fare']]
dataset_X = dataset_X.values
dataset_X

array([[ 1.    , 22.    ,  3.    ,  1.    ,  0.    ,  7.25  ],
       [ 0.    , 38.    ,  1.    ,  1.    ,  0.    , 71.2833],
       [ 0.    , 26.    ,  3.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  0.    ,  3.    ,  1.    ,  2.    , 23.45  ],
       [ 1.    , 26.    ,  1.    ,  0.    ,  0.    , 30.    ],
       [ 1.    , 32.    ,  3.    ,  0.    ,  0.    ,  7.75  ]])

In [4]:
# 两种分类结果分别是幸存和死亡，‘Survived’字段是其中一种分类标签
# 新增‘Deceased’表示第二种分类标签，取值为‘Survived’字段取非
data['Deceased'] = data['Survived'].apply(lambda s:int(not s))
data['Deceased']

0      1
1      0
2      0
3      0
4      1
5      1
6      1
7      1
8      0
9      0
10     0
11     0
12     1
13     1
14     1
15     0
16     1
17     0
18     1
19     0
20     1
21     0
22     0
23     0
24     1
25     0
26     1
27     1
28     0
29     1
      ..
861    1
862    0
863    1
864    1
865    0
866    0
867    1
868    1
869    0
870    1
871    0
872    1
873    1
874    0
875    0
876    1
877    1
878    1
879    0
880    0
881    1
882    1
883    1
884    1
885    1
886    1
887    0
888    1
889    0
890    1
Name: Deceased, Length: 891, dtype: int64

In [5]:
dataset_Y = data[['Deceased', 'Survived']]
dataset_Y = dataset_Y.values
dataset_Y

array([[1, 0],
       [0, 1],
       [0, 1],
       ...,
       [1, 0],
       [0, 1],
       [1, 0]], dtype=int64)

In [6]:
from sklearn.model_selection import train_test_split

# 划分为训练集和验证集
X_train, X_val, Y_train, Y_val = train_test_split(dataset_X, dataset_Y, test_size=0.2, random_state=42)

In [22]:
import tensorflow as tf

## 构建计算图

# 声明输入数据占位符
X = tf.placeholder(tf.float32, shape=[None, 6])
Y = tf.placeholder(tf.float32, shape=[None, 2])

# 声明变量
W1 = tf.Variable(tf.truncated_normal([6,4]), name='weights_1')
b1 = tf.Variable(tf.zeros([1,4]), name='bias_1')
W2 = tf.Variable(tf.truncated_normal([4,2]),name='weights_2')
b2 = tf.Variable(tf.zeros([2]), name='bias_2')

# 构造前向传播计算图
z1 = tf.matmul(X, W1) + b1
y_pred = tf.nn.softmax(tf.matmul(z1, W2) + b2)

# 使用交叉熵作为损失函数
cross_entropy = -tf.reduce_sum(Y * tf.log(y_pred + 1e-10),reduction_indices=1)

# 批量样本的代价值为所有样本交叉熵的平均值
cost = tf.reduce_mean(cross_entropy)

# 加入优化算法
train_op = tf.train.AdamOptimizer(0.001).minimize(cost)

In [23]:
## 训练迭代

with tf.Session() as sess:
    # 初始化所有变量
    tf.global_variables_initializer().run()
    
    # 迭代训练
    for epoch in range(500):
        total_loss = 0
        for i in range(len(X_train)):
            feed = {X:[X_train[i]], Y:[Y_train[i]]}
            _,loss = sess.run([train_op, cost], feed_dict=feed)
            total_loss += loss
        print('Epoch: %04d, total loss=%.9f' % (epoch + 1,total_loss))
    print('Training complete!')
    
    ## 评估验证集的准确率

    pred = sess.run(y_pred, feed_dict={X:X_val})
    correct = np.equal(np.argmax(pred, 1), np.argmax(Y_val, 1))
    accuracy = np.mean(correct.astype(np.float32))
    print("Accuracy on test set: %.9f" % accuracy)
    
    ## 测试测试集数据
    testdata = pd.read_csv("D:/cao/kaggle/Titanic/data/test.csv")
    testdata = testdata.fillna(0)
    # convert ['male', 'female'] values of Sex to [1, 0]
    testdata['Sex'] = testdata['Sex'].apply(lambda s: 1 if s == 'male' else 0)
    X_test = testdata[['Sex', 'Age', 'Pclass', 'SibSp', 'Parch', 'Fare']]
    predictions = np.argmax(sess.run(y_pred, feed_dict={X: X_test}), 1)
    
    ## 将结果导出为csv文件
    submission = pd.DataFrame({
        "PassengerId": testdata["PassengerId"],
        "Survived": predictions
    })
    submission.to_csv("titanic-submission.csv", index=False)

Epoch: 0001, total loss=5546.903262723
Epoch: 0002, total loss=4498.115071389
Epoch: 0003, total loss=2167.997049432
Epoch: 0004, total loss=648.877790437
Epoch: 0005, total loss=542.466192416
Epoch: 0006, total loss=496.461688609
Epoch: 0007, total loss=468.163735916
Epoch: 0008, total loss=450.270260985
Epoch: 0009, total loss=439.205251625
Epoch: 0010, total loss=432.418005270
Epoch: 0011, total loss=428.141939776
Epoch: 0012, total loss=425.230706785
Epoch: 0013, total loss=423.057553034
Epoch: 0014, total loss=421.316044566
Epoch: 0015, total loss=419.861635665
Epoch: 0016, total loss=418.612131733
Epoch: 0017, total loss=417.518599184
Epoch: 0018, total loss=416.556961536
Epoch: 0019, total loss=415.690809250
Epoch: 0020, total loss=414.912641232
Epoch: 0021, total loss=414.199637913
Epoch: 0022, total loss=413.547336152
Epoch: 0023, total loss=412.937217863
Epoch: 0024, total loss=412.365919689
Epoch: 0025, total loss=411.821853700
Epoch: 0026, total loss=411.302656802
Epoch: 0027, total loss=410.794651907
Epoch: 0028, total loss=410.301768401
Epoch: 0029, total loss=409.815418038
Epoch: 0030, total loss=409.332622861
Epoch: 0031, total loss=408.851486562
Epoch: 0032, total loss=408.373887052
Epoch: 0033, total loss=407.896248057
Epoch: 0034, total loss=407.421941843
Epoch: 0035, total loss=406.948991131
Epoch: 0036, total loss=406.480788455
Epoch: 0037, total loss=406.015780572
Epoch: 0038, total loss=405.554819261
Epoch: 0039, total loss=405.101392811
Epoch: 0040, total loss=404.652853914
Epoch: 0041, total loss=404.211748915
Epoch: 0042, total loss=403.777166620
Epoch: 0043, total loss=403.349747801
Epoch: 0044, total loss=402.929714012
Epoch: 0045, total loss=402.516333379
Epoch: 0046, total loss=402.110929219
Epoch: 0047, total loss=401.712333005
Epoch: 0048, total loss=401.320863353
Epoch: 0049, total loss=400.937137309
Epoch: 0050, total loss=400.559490611
Epoch: 0051, total loss=400.187718175
Epoch: 0052, total loss=399.822843877
Epoch: 0053, total loss=399.463133953
Epoch: 0054, total loss=399.109657415
Epoch: 0055, total loss=398.761185614
Epoch: 0056, total loss=398.418535975
Epoch: 0057, total loss=398.079644985
Epoch: 0058, total loss=397.746250041
Epoch: 0059, total loss=397.416348441
Epoch: 0060, total loss=397.090273881
Epoch: 0061, total loss=396.768823608
Epoch: 0062, total loss=396.449884367
Epoch: 0063, total loss=396.134915251
Epoch: 0064, total loss=395.823204038
Epoch: 0065, total loss=395.514212221
Epoch: 0066, total loss=395.206815935
Epoch: 0067, total loss=394.903104224
Epoch: 0068, total loss=394.601073571
Epoch: 0069, total loss=394.301075441
Epoch: 0070, total loss=394.003385400
Epoch: 0071, total loss=393.706697924
Epoch: 0072, total loss=393.411598534
Epoch: 0073, total loss=393.119292561
Epoch: 0074, total loss=392.827036360
Epoch: 0075, total loss=392.536329227
Epoch: 0076, total loss=392.245963147
Epoch: 0077, total loss=391.957562561
Epoch: 0078, total loss=391.668681841
Epoch: 0079, total loss=391.381184908
Epoch: 0080, total loss=391.094519285
Epoch: 0081, total loss=390.808096110
Epoch: 0082, total loss=390.522102447
Epoch: 0083, total loss=390.235920464
Epoch: 0084, total loss=389.950487948
Epoch: 0085, total loss=389.664601205
Epoch: 0086, total loss=389.379114336
Epoch: 0087, total loss=389.093548166
Epoch: 0088, total loss=388.807935422
Epoch: 0089, total loss=388.521828262
Epoch: 0090, total loss=388.235011192
Epoch: 0091, total loss=387.948970872
Epoch: 0092, total loss=387.661800554
Epoch: 0093, total loss=387.373935691
Epoch: 0094, total loss=387.085994660
Epoch: 0095, total loss=386.797635656
Epoch: 0096, total loss=386.508625418
Epoch: 0097, total loss=386.218323083
Epoch: 0098, total loss=385.927307817
Epoch: 0099, total loss=385.636078173
Epoch: 0100, total loss=385.343685674
Epoch: 0101, total loss=385.050546039
Epoch: 0102, total loss=384.755808595
Epoch: 0103, total loss=384.460374160
Epoch: 0104, total loss=384.164622613
Epoch: 0105, total loss=383.866240200
Epoch: 0106, total loss=383.567479207
Epoch: 0107, total loss=383.267753455
Epoch: 0108, total loss=382.966487453
Epoch: 0109, total loss=382.663134544
Epoch: 0110, total loss=382.358604854
Epoch: 0111, total loss=382.052530174
Epoch: 0112, total loss=381.745252390
Epoch: 0113, total loss=381.435733895
Epoch: 0114, total loss=381.125286802
Epoch: 0115, total loss=380.811766430
Epoch: 0116, total loss=380.497296189
Epoch: 0117, total loss=380.180337625
Epoch: 0118, total loss=379.860663864
Epoch: 0119, total loss=379.538835698
Epoch: 0120, total loss=379.215042411
Epoch: 0121, total loss=378.888445516
Epoch: 0122, total loss=378.559677133
Epoch: 0123, total loss=378.227358527
Epoch: 0124, total loss=377.892517354
Epoch: 0125, total loss=377.555280283
Epoch: 0126, total loss=377.214823255
Epoch: 0127, total loss=376.871052271
Epoch: 0128, total loss=376.525199732
Epoch: 0129, total loss=376.176450776
Epoch: 0130, total loss=375.825961843
Epoch: 0131, total loss=375.474419634
Epoch: 0132, total loss=375.124312393
Epoch: 0133, total loss=374.777296774
Epoch: 0134, total loss=374.436860193
Epoch: 0135, total loss=374.105832937
Epoch: 0136, total loss=373.789382715
Epoch: 0137, total loss=373.490063862
Epoch: 0138, total loss=373.205910670
Epoch: 0139, total loss=372.936704732
Epoch: 0140, total loss=372.681798343
Epoch: 0141, total loss=372.443068140
Epoch: 0142, total loss=372.220860851
Epoch: 0143, total loss=372.014633938
Epoch: 0144, total loss=371.820331338
Epoch: 0145, total loss=371.633020021
Epoch: 0146, total loss=371.447591427
Epoch: 0147, total loss=371.264918195
Epoch: 0148, total loss=371.083471145
Epoch: 0149, total loss=370.903750850
Epoch: 0150, total loss=370.724840632
Epoch: 0151, total loss=370.547569014
Epoch: 0152, total loss=370.370506888
Epoch: 0153, total loss=370.194249940
Epoch: 0154, total loss=370.018454331
Epoch: 0155, total loss=369.842814855
Epoch: 0156, total loss=369.667931910
Epoch: 0157, total loss=369.493890248
Epoch: 0158, total loss=369.320370793
Epoch: 0159, total loss=369.148872332
Epoch: 0160, total loss=368.978873359
Epoch: 0161, total loss=368.809947605
Epoch: 0162, total loss=368.643770052
Epoch: 0163, total loss=368.478771176
Epoch: 0164, total loss=368.315858282
Epoch: 0165, total loss=368.153616100
Epoch: 0166, total loss=367.991812588
Epoch: 0167, total loss=367.829989378
Epoch: 0168, total loss=367.668297045
Epoch: 0169, total loss=367.505153244
Epoch: 0170, total loss=367.342426655
Epoch: 0171, total loss=367.179194668
Epoch: 0172, total loss=367.015314169
Epoch: 0173, total loss=366.851196881
Epoch: 0174, total loss=366.686207962
Epoch: 0175, total loss=366.521282414
Epoch: 0176, total loss=366.355847480
Epoch: 0177, total loss=366.190182691
Epoch: 0178, total loss=366.024272819
Epoch: 0179, total loss=365.858101674
Epoch: 0180, total loss=365.691497829
Epoch: 0181, total loss=365.524779308
Epoch: 0182, total loss=365.358254391
Epoch: 0183, total loss=365.191313495
Epoch: 0184, total loss=365.023858015
Epoch: 0185, total loss=364.856421635
Epoch: 0186, total loss=364.688989270
Epoch: 0187, total loss=364.520910152
Epoch: 0188, total loss=364.353422807
Epoch: 0189, total loss=364.185250225
Epoch: 0190, total loss=364.017007176
Epoch: 0191, total loss=363.848444998
Epoch: 0192, total loss=363.679627755
Epoch: 0193, total loss=363.511137839
Epoch: 0194, total loss=363.342140043
Epoch: 0195, total loss=363.172670582
Epoch: 0196, total loss=363.003224191
Epoch: 0197, total loss=362.833750309
Epoch: 0198, total loss=362.663755878
Epoch: 0199, total loss=362.493366721
Epoch: 0200, total loss=362.323379968
Epoch: 0201, total loss=362.152499349
Epoch: 0202, total loss=361.981485379
Epoch: 0203, total loss=361.809841087
Epoch: 0204, total loss=361.638377503
Epoch: 0205, total loss=361.466184970
Epoch: 0206, total loss=361.293648178
Epoch: 0207, total loss=361.120139277
Epoch: 0208, total loss=360.947024748
Epoch: 0209, total loss=360.772287414
Epoch: 0210, total loss=360.598132098
Epoch: 0211, total loss=360.422036698
Epoch: 0212, total loss=360.247474783
Epoch: 0213, total loss=360.068212603
Epoch: 0214, total loss=359.894715986
Epoch: 0215, total loss=359.710336291
Epoch: 0216, total loss=359.540142591
Epoch: 0217, total loss=359.346988295
Epoch: 0218, total loss=359.187783059
Epoch: 0219, total loss=358.978690416
Epoch: 0220, total loss=358.843111867
Epoch: 0221, total loss=358.622708658
Epoch: 0222, total loss=358.491869355
Epoch: 0223, total loss=358.258885975
Epoch: 0224, total loss=358.116589454
Epoch: 0225, total loss=357.844209112
Epoch: 0226, total loss=357.752926148
Epoch: 0227, total loss=357.449862301
Epoch: 0228, total loss=357.368718809
Epoch: 0229, total loss=357.024898091
Epoch: 0230, total loss=356.981944432
Epoch: 0231, total loss=356.595030189
Epoch: 0232, total loss=356.576138336
Epoch: 0233, total loss=356.140822362
Epoch: 0234, total loss=356.152751715
Epoch: 0235, total loss=355.668372888
Epoch: 0236, total loss=355.700597658
Epoch: 0237, total loss=355.174182266
Epoch: 0238, total loss=355.213446252
Epoch: 0239, total loss=354.668677684
Epoch: 0240, total loss=354.700635469
Epoch: 0241, total loss=354.187907971
Epoch: 0242, total loss=354.202812701
Epoch: 0243, total loss=353.789167454
Epoch: 0244, total loss=353.791735496
Epoch: 0245, total loss=353.522924148
Epoch: 0246, total loss=353.531375716
Epoch: 0247, total loss=353.373641424
Epoch: 0248, total loss=353.356121650
Epoch: 0249, total loss=353.207095097
Epoch: 0250, total loss=353.144077020
Epoch: 0251, total loss=352.981667090
Epoch: 0252, total loss=352.908389969
Epoch: 0253, total loss=352.740826658
Epoch: 0254, total loss=352.672856229
Epoch: 0255, total loss=352.498735216
Epoch: 0256, total loss=352.440307877
Epoch: 0257, total loss=352.257027563
Epoch: 0258, total loss=352.209138873
Epoch: 0259, total loss=352.016900813
Epoch: 0260, total loss=351.978202089
Epoch: 0261, total loss=351.779076398
Epoch: 0262, total loss=351.745708319
Epoch: 0263, total loss=351.543787516
Epoch: 0264, total loss=351.511491098
Epoch: 0265, total loss=351.311166832
Epoch: 0266, total loss=351.275332244
Epoch: 0267, total loss=351.080322011
Epoch: 0268, total loss=351.037960225
Epoch: 0269, total loss=350.851202494
Epoch: 0270, total loss=350.800453951
Epoch: 0271, total loss=350.623721451
Epoch: 0272, total loss=350.563395104
Epoch: 0273, total loss=350.397392048
Epoch: 0274, total loss=350.327888791
Epoch: 0275, total loss=350.172502131
Epoch: 0276, total loss=350.094212824
Epoch: 0277, total loss=349.949141084
Epoch: 0278, total loss=349.862982194
Epoch: 0279, total loss=349.727488951
Epoch: 0280, total loss=349.635004404
Epoch: 0281, total loss=349.507785133
Epoch: 0282, total loss=349.411251604
Epoch: 0283, total loss=349.291448155
Epoch: 0284, total loss=349.192689487
Epoch: 0285, total loss=349.080518075
Epoch: 0286, total loss=348.983602337
Epoch: 0287, total loss=348.882401831
Epoch: 0288, total loss=348.793725567
Epoch: 0289, total loss=348.695438997
Epoch: 0290, total loss=348.599503216
Epoch: 0291, total loss=348.510801795
Epoch: 0292, total loss=348.413754049
Epoch: 0293, total loss=348.311769631
Epoch: 0294, total loss=348.206909539
Epoch: 0295, total loss=348.099472946
Epoch: 0296, total loss=347.993022169
Epoch: 0297, total loss=347.884899214
Epoch: 0298, total loss=347.777531717
Epoch: 0299, total loss=347.669101703
Epoch: 0300, total loss=347.560651033
Epoch: 0301, total loss=347.451465228
Epoch: 0302, total loss=347.342039986
Epoch: 0303, total loss=347.231682622
Epoch: 0304, total loss=347.121263158
Epoch: 0305, total loss=347.010153427
Epoch: 0306, total loss=346.898473396
Epoch: 0307, total loss=346.786227117
Epoch: 0308, total loss=346.673720124
Epoch: 0309, total loss=346.560412285
Epoch: 0310, total loss=346.446898442
Epoch: 0311, total loss=346.333024790
Epoch: 0312, total loss=346.218949904
Epoch: 0313, total loss=346.104515705
Epoch: 0314, total loss=345.990126052
Epoch: 0315, total loss=345.875803755
Epoch: 0316, total loss=345.761932670
Epoch: 0317, total loss=345.648298257
Epoch: 0318, total loss=345.535367934
Epoch: 0319, total loss=345.422673791
Epoch: 0320, total loss=345.310899716
Epoch: 0321, total loss=345.199214466
Epoch: 0322, total loss=345.088487339
Epoch: 0323, total loss=344.977905398
Epoch: 0324, total loss=344.867818554
Epoch: 0325, total loss=344.758128400
Epoch: 0326, total loss=344.648781545
Epoch: 0327, total loss=344.539702184
Epoch: 0328, total loss=344.430874721
Epoch: 0329, total loss=344.322240734
Epoch: 0330, total loss=344.214092928
Epoch: 0331, total loss=344.105950193
Epoch: 0332, total loss=343.998073669
Epoch: 0333, total loss=343.890406744
Epoch: 0334, total loss=343.782921288
Epoch: 0335, total loss=343.675529427
Epoch: 0336, total loss=343.568636115
Epoch: 0337, total loss=343.461614728
Epoch: 0338, total loss=343.354979305
Epoch: 0339, total loss=343.248656279
Epoch: 0340, total loss=343.142332005
Epoch: 0341, total loss=343.036346673
Epoch: 0342, total loss=342.930374805
Epoch: 0343, total loss=342.824642777
Epoch: 0344, total loss=342.719223420
Epoch: 0345, total loss=342.613905004
Epoch: 0346, total loss=342.508444248
Epoch: 0347, total loss=342.403698578
Epoch: 0348, total loss=342.298791526
Epoch: 0349, total loss=342.194087167
Epoch: 0350, total loss=342.089638426
Epoch: 0351, total loss=341.984966386
Epoch: 0352, total loss=341.880458610
Epoch: 0353, total loss=341.776126879
Epoch: 0354, total loss=341.671694247
Epoch: 0355, total loss=341.567378907
Epoch: 0356, total loss=341.462937236
Epoch: 0357, total loss=341.358311640
Epoch: 0358, total loss=341.253783122
Epoch: 0359, total loss=341.148966830
Epoch: 0360, total loss=341.044028195
Epoch: 0361, total loss=340.938685186
Epoch: 0362, total loss=340.833424354
Epoch: 0363, total loss=340.727697570
Epoch: 0364, total loss=340.621802724
Epoch: 0365, total loss=340.515665399
Epoch: 0366, total loss=340.409007407
Epoch: 0367, total loss=340.302491695
Epoch: 0368, total loss=340.195484485
Epoch: 0369, total loss=340.088456458
Epoch: 0370, total loss=339.981206476
Epoch: 0371, total loss=339.873631105
Epoch: 0372, total loss=339.766290892
Epoch: 0373, total loss=339.658644371
Epoch: 0374, total loss=339.551295659
Epoch: 0375, total loss=339.444156371
Epoch: 0376, total loss=339.337078364
Epoch: 0377, total loss=339.230351551
Epoch: 0378, total loss=339.124092156
Epoch: 0379, total loss=339.018499034
Epoch: 0380, total loss=338.913360621
Epoch: 0381, total loss=338.809002531
Epoch: 0382, total loss=338.705608610
Epoch: 0383, total loss=338.603209781
Epoch: 0384, total loss=338.501751589
Epoch: 0385, total loss=338.401328699
Epoch: 0386, total loss=338.302062425
Epoch: 0387, total loss=338.203436021
Epoch: 0388, total loss=338.106257563
Epoch: 0389, total loss=338.010055559
Epoch: 0390, total loss=337.914642816
Epoch: 0391, total loss=337.820416448
Epoch: 0392, total loss=337.727222052
Epoch: 0393, total loss=337.634953405
Epoch: 0394, total loss=337.543806958
Epoch: 0395, total loss=337.453538012
Epoch: 0396, total loss=337.364345658
Epoch: 0397, total loss=337.276306824
Epoch: 0398, total loss=337.189192326
Epoch: 0399, total loss=337.103204078
Epoch: 0400, total loss=337.018269061
Epoch: 0401, total loss=336.934376427
Epoch: 0402, total loss=336.851581221
Epoch: 0403, total loss=336.769987318
Epoch: 0404, total loss=336.689476565
Epoch: 0405, total loss=336.610157148
Epoch: 0406, total loss=336.532054300
Epoch: 0407, total loss=336.454979293
Epoch: 0408, total loss=336.379197864
Epoch: 0409, total loss=336.304677672
Epoch: 0410, total loss=336.231332191
Epoch: 0411, total loss=336.159388394
Epoch: 0412, total loss=336.088525541
Epoch: 0413, total loss=336.019221955
Epoch: 0414, total loss=335.951106006
Epoch: 0415, total loss=335.884551509
Epoch: 0416, total loss=335.819278919
Epoch: 0417, total loss=335.755658400
Epoch: 0418, total loss=335.693474431
Epoch: 0419, total loss=335.633020462
Epoch: 0420, total loss=335.574262504
Epoch: 0421, total loss=335.517044437
Epoch: 0422, total loss=335.461933559
Epoch: 0423, total loss=335.408534687
Epoch: 0424, total loss=335.357234548
Epoch: 0425, total loss=335.307909255
Epoch: 0426, total loss=335.260829463
Epoch: 0427, total loss=335.215916282
Epoch: 0428, total loss=335.173335195
Epoch: 0429, total loss=335.132923217
Epoch: 0430, total loss=335.094850783
Epoch: 0431, total loss=335.059170756
Epoch: 0432, total loss=335.025545658
Epoch: 0433, total loss=334.994070766
Epoch: 0434, total loss=334.964671814
Epoch: 0435, total loss=334.937171064
Epoch: 0436, total loss=334.911287271
Epoch: 0437, total loss=334.887145068
Epoch: 0438, total loss=334.864316599
Epoch: 0439, total loss=334.842888648
Epoch: 0440, total loss=334.822533472
Epoch: 0441, total loss=334.803308424
Epoch: 0442, total loss=334.784917815
Epoch: 0443, total loss=334.767480998
Epoch: 0444, total loss=334.750748180
Epoch: 0445, total loss=334.734621306
Epoch: 0446, total loss=334.719099889
Epoch: 0447, total loss=334.704164062
Epoch: 0448, total loss=334.689658907
Epoch: 0449, total loss=334.675662967
Epoch: 0450, total loss=334.661908024
Epoch: 0451, total loss=334.648503146
Epoch: 0452, total loss=334.635417579
Epoch: 0453, total loss=334.622572389
Epoch: 0454, total loss=334.609927460
Epoch: 0455, total loss=334.597557420
Epoch: 0456, total loss=334.585296916
Epoch: 0457, total loss=334.573258441
Epoch: 0458, total loss=334.561172275
Epoch: 0459, total loss=334.549339303
Epoch: 0460, total loss=334.537603240
Epoch: 0461, total loss=334.525952112
Epoch: 0462, total loss=334.514398650
Epoch: 0463, total loss=334.502880465
Epoch: 0464, total loss=334.491470397
Epoch: 0465, total loss=334.480101773
Epoch: 0466, total loss=334.468754102
Epoch: 0467, total loss=334.457527651
Epoch: 0468, total loss=334.446290371
Epoch: 0469, total loss=334.435097454
Epoch: 0470, total loss=334.424039899
Epoch: 0471, total loss=334.412990278
Epoch: 0472, total loss=334.401961770
Epoch: 0473, total loss=334.391015727
Epoch: 0474, total loss=334.380082562
Epoch: 0475, total loss=334.369176805
Epoch: 0476, total loss=334.358389081
Epoch: 0477, total loss=334.347575558
Epoch: 0478, total loss=334.336856198
Epoch: 0479, total loss=334.326173602
Epoch: 0480, total loss=334.315512426
Epoch: 0481, total loss=334.304927558
Epoch: 0482, total loss=334.294458602
Epoch: 0483, total loss=334.283935745
Epoch: 0484, total loss=334.273566068
Epoch: 0485, total loss=334.263174373
Epoch: 0486, total loss=334.252799353
Epoch: 0487, total loss=334.242542551
Epoch: 0488, total loss=334.232336943
Epoch: 0489, total loss=334.222208496
Epoch: 0490, total loss=334.212113876
Epoch: 0491, total loss=334.202093909
Epoch: 0492, total loss=334.192079308
Epoch: 0493, total loss=334.182143797
Epoch: 0494, total loss=334.172326170
Epoch: 0495, total loss=334.162488964
Epoch: 0496, total loss=334.152688808
Epoch: 0497, total loss=334.142982276
Epoch: 0498, total loss=334.133314954
Epoch: 0499, total loss=334.123676914
Epoch: 0500, total loss=334.114117325
Training complete!
Accuracy on test set: 0.793296099