### 1. 数据预处理

In [1]:
import pandas as pd
import numpy as np

## 读取数据信息
data = pd.read_csv("E:/Deep Learning/kaggle/Titanic/data/train.csv")
data.info()
data.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
# 取部分特征用于分类
data['Sex'] = data['Sex'].apply(lambda s:1 if s == 'male' else 0)
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# 将所有缺失的字段填充为0
data = data.fillna(0)
dataset_X = data[['Sex', 'Age', 'Pclass', 'SibSp', 'Parch', 'Fare']]
dataset_X = dataset_X.values
dataset_X

array([[ 1.    , 22.    ,  3.    ,  1.    ,  0.    ,  7.25  ],
       [ 0.    , 38.    ,  1.    ,  1.    ,  0.    , 71.2833],
       [ 0.    , 26.    ,  3.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  0.    ,  3.    ,  1.    ,  2.    , 23.45  ],
       [ 1.    , 26.    ,  1.    ,  0.    ,  0.    , 30.    ],
       [ 1.    , 32.    ,  3.    ,  0.    ,  0.    ,  7.75  ]])

In [4]:
# 两种分类分别是幸存和死亡，‘Survived’字段是其中一种分类标签
# 新增‘Deceased’表示第二种分类标签，取值为‘Survived’字段取非
data['Deceased'] = data['Survived'].apply(lambda s:int(not s))
data['Deceased']

0      1
1      0
2      0
3      0
4      1
5      1
6      1
7      1
8      0
9      0
10     0
11     0
12     1
13     1
14     1
15     0
16     1
17     0
18     1
19     0
20     1
21     0
22     0
23     0
24     1
25     0
26     1
27     1
28     0
29     1
      ..
861    1
862    0
863    1
864    1
865    0
866    0
867    1
868    1
869    0
870    1
871    0
872    1
873    1
874    0
875    0
876    1
877    1
878    1
879    0
880    0
881    1
882    1
883    1
884    1
885    1
886    1
887    0
888    1
889    0
890    1
Name: Deceased, Length: 891, dtype: int64

In [5]:
dataset_Y = data[['Deceased', 'Survived']]
dataset_Y = dataset_Y.values
dataset_Y

array([[1, 0],
       [0, 1],
       [0, 1],
       ...,
       [1, 0],
       [0, 1],
       [1, 0]], dtype=int64)

In [6]:
from sklearn.model_selection import train_test_split

# 划分为训练集和验证集
X_train, X_val, Y_train, Y_val = train_test_split(dataset_X, dataset_Y, test_size=0.2, random_state=42)

In [7]:
import tensorflow as tf

## 构建计算图

# 声明输入数据占位符
X = tf.placeholder(tf.float32, shape=[None, 6])
Y = tf.placeholder(tf.float32, shape=[None, 2])

# 声明变量
W = tf.Variable(tf.truncated_normal([6,2]), name='weights')
b = tf.Variable(tf.zeros([2]), name='bias')

# 构造前向传播计算图
y_pred = tf.nn.softmax(tf.matmul(X, W) + b)

# 使用交叉熵作为损失函数
cross_entropy = -tf.reduce_sum(Y * tf.log(y_pred + 1e-10),reduction_indices=1)

# 批量样本的代价值为所有样本交叉熵的平均值
cost = tf.reduce_mean(cross_entropy)

# 加入优化算法
train_op = tf.train.AdamOptimizer(0.001).minimize(cost)

In [8]:
## 训练迭代

with tf.Session() as sess:
    # 初始化所有变量
    tf.global_variables_initializer().run()
    
    # 迭代训练
    for epoch in range(500):
        total_loss = 0
        for i in range(len(X_train)):
            feed = {X:[X_train[i]], Y:[Y_train[i]]}
            _,loss = sess.run([train_op, cost], feed_dict=feed)
            total_loss += loss
        print('Epoch: %04d, total loss=%.9f' % (epoch + 1,total_loss))
    print('Training complete!')
    
    ## 评估验证集的准确率

    pred = sess.run(y_pred, feed_dict={X:X_val})
    correct = np.equal(np.argmax(pred, 1), np.argmax(Y_val, 1))
    accuracy = np.mean(correct.astype(np.float32))
    print("Accuracy on test set: %.9f" % accuracy)
    
    ## 测试测试集数据
    testdata = pd.read_csv("E:/Deep Learning/kaggle/Titanic/data/test.csv")
    testdata = testdata.fillna(0)
    # convert ['male', 'female'] values of Sex to [1, 0]
    testdata['Sex'] = testdata['Sex'].apply(lambda s: 1 if s == 'male' else 0)
    X_test = testdata[['Sex', 'Age', 'Pclass', 'SibSp', 'Parch', 'Fare']]
    predictions = np.argmax(sess.run(y_pred, feed_dict={X: X_test}), 1)
    
    ## 将结果导出为csv文件
    submission = pd.DataFrame({
        "PassengerId": testdata["PassengerId"],
        "Survived": predictions
    })
    submission.to_csv("titanic-submission.csv", index=False)

Epoch: 0001, total loss=8041.801799315
Epoch: 0002, total loss=5840.885838464
Epoch: 0003, total loss=4792.652625477
Epoch: 0004, total loss=4431.528784425
Epoch: 0005, total loss=3681.042715555
Epoch: 0006, total loss=1760.565615867
Epoch: 0007, total loss=963.491425088
Epoch: 0008, total loss=844.843407869
Epoch: 0009, total loss=739.399570923
Epoch: 0010, total loss=643.133343786
Epoch: 0011, total loss=558.368760413
Epoch: 0012, total loss=487.933949998
Epoch: 0013, total loss=434.096129134
Epoch: 0014, total loss=397.170500459
Epoch: 0015, total loss=374.574290305
Epoch: 0016, total loss=361.913522684
Epoch: 0017, total loss=355.159108008
Epoch: 0018, total loss=351.632321288
Epoch: 0019, total loss=349.783677510
Epoch: 0020, total loss=348.762320325
Epoch: 0021, total loss=348.137828822
Epoch: 0022, total loss=347.708943395
Epoch: 0023, total loss=347.386069703
Epoch: 0024, total loss=347.128230328
Epoch: 0025, total loss=346.914480950
Epoch: 0026, total loss=346.733098115
Epoch: 0027, total loss=346.576287243
Epoch: 0028, total loss=346.438858877
Epoch: 0029, total loss=346.316948782
Epoch: 0030, total loss=346.207175771
Epoch: 0031, total loss=346.107521266
Epoch: 0032, total loss=346.016361409
Epoch: 0033, total loss=345.932186591
Epoch: 0034, total loss=345.853672407
Epoch: 0035, total loss=345.780770601
Epoch: 0036, total loss=345.712113409
Epoch: 0037, total loss=345.647444122
Epoch: 0038, total loss=345.586490944
Epoch: 0039, total loss=345.528848038
Epoch: 0040, total loss=345.474117508
Epoch: 0041, total loss=345.421989949
Epoch: 0042, total loss=345.372575777
Epoch: 0043, total loss=345.325656340
Epoch: 0044, total loss=345.280702621
Epoch: 0045, total loss=345.238220687
Epoch: 0046, total loss=345.197591181
Epoch: 0047, total loss=345.158767535
Epoch: 0048, total loss=345.121931739
Epoch: 0049, total loss=345.086735946
Epoch: 0050, total loss=345.053093305
Epoch: 0051, total loss=345.021271614
Epoch: 0052, total loss=344.990710504
Epoch: 0053, total loss=344.961577954
Epoch: 0054, total loss=344.934025994
Epoch: 0055, total loss=344.907903395
Epoch: 0056, total loss=344.882613888
Epoch: 0057, total loss=344.858762054
Epoch: 0058, total loss=344.835953003
Epoch: 0059, total loss=344.814287655
Epoch: 0060, total loss=344.793860339
Epoch: 0061, total loss=344.774358931
Epoch: 0062, total loss=344.755836033
Epoch: 0063, total loss=344.738123994
Epoch: 0064, total loss=344.721590403
Epoch: 0065, total loss=344.705562227
Epoch: 0066, total loss=344.690614445
Epoch: 0067, total loss=344.676409782
Epoch: 0068, total loss=344.662901886
Epoch: 0069, total loss=344.650128132
Epoch: 0070, total loss=344.638157092
Epoch: 0071, total loss=344.626795050
Epoch: 0072, total loss=344.616001909
Epoch: 0073, total loss=344.606001486
Epoch: 0074, total loss=344.596411156
Epoch: 0075, total loss=344.587463260
Epoch: 0076, total loss=344.579075623
Epoch: 0077, total loss=344.571222931
Epoch: 0078, total loss=344.563901128
Epoch: 0079, total loss=344.556831733
Epoch: 0080, total loss=344.550540544
Epoch: 0081, total loss=344.544558710
Epoch: 0082, total loss=344.538938932
Epoch: 0083, total loss=344.533597283
Epoch: 0084, total loss=344.528919257
Epoch: 0085, total loss=344.524533078
Epoch: 0086, total loss=344.520386169
Epoch: 0087, total loss=344.516736152
Epoch: 0088, total loss=344.513368827
Epoch: 0089, total loss=344.510227204
Epoch: 0090, total loss=344.507385947
Epoch: 0091, total loss=344.504912657
Epoch: 0092, total loss=344.502595886
Epoch: 0093, total loss=344.500502992
Epoch: 0094, total loss=344.498986647
Epoch: 0095, total loss=344.497371471
Epoch: 0096, total loss=344.496055468
Epoch: 0097, total loss=344.495063908
Epoch: 0098, total loss=344.494276815
Epoch: 0099, total loss=344.493473694
Epoch: 0100, total loss=344.493158377
Epoch: 0101, total loss=344.492765131
Epoch: 0102, total loss=344.492510223
Epoch: 0103, total loss=344.492749370
Epoch: 0104, total loss=344.492873474
Epoch: 0105, total loss=344.493132628
Epoch: 0106, total loss=344.493701341
Epoch: 0107, total loss=344.494387087
Epoch: 0108, total loss=344.494944592
Epoch: 0109, total loss=344.495877069
Epoch: 0110, total loss=344.496927982
Epoch: 0111, total loss=344.497960650
Epoch: 0112, total loss=344.499047976
Epoch: 0113, total loss=344.500295329
Epoch: 0114, total loss=344.501738657
Epoch: 0115, total loss=344.503016193
Epoch: 0116, total loss=344.504733827
Epoch: 0117, total loss=344.506171891
Epoch: 0118, total loss=344.507866102
Epoch: 0119, total loss=344.509732572
Epoch: 0120, total loss=344.511358792
Epoch: 0121, total loss=344.513396840
Epoch: 0122, total loss=344.515170438
Epoch: 0123, total loss=344.517108284
Epoch: 0124, total loss=344.519232344
Epoch: 0125, total loss=344.521280719
Epoch: 0126, total loss=344.523409521
Epoch: 0127, total loss=344.525569058
Epoch: 0128, total loss=344.527678550
Epoch: 0129, total loss=344.529912093
Epoch: 0130, total loss=344.532149743
Epoch: 0131, total loss=344.534440736
Epoch: 0132, total loss=344.536858015
Epoch: 0133, total loss=344.539159013
Epoch: 0134, total loss=344.541472389
Epoch: 0135, total loss=344.543794733
Epoch: 0136, total loss=344.546108196
Epoch: 0137, total loss=344.548658444
Epoch: 0138, total loss=344.551017924
Epoch: 0139, total loss=344.553477099
Epoch: 0140, total loss=344.555818198
Epoch: 0141, total loss=344.558368890
Epoch: 0142, total loss=344.560602165
Epoch: 0143, total loss=344.563235696
Epoch: 0144, total loss=344.565559123
Epoch: 0145, total loss=344.568239456
Epoch: 0146, total loss=344.570548096
Epoch: 0147, total loss=344.573073451
Epoch: 0148, total loss=344.575522008
Epoch: 0149, total loss=344.577905104
Epoch: 0150, total loss=344.580387946
Epoch: 0151, total loss=344.582883222
Epoch: 0152, total loss=344.585263724
Epoch: 0153, total loss=344.587601650
Epoch: 0154, total loss=344.590072887
Epoch: 0155, total loss=344.592507551
Epoch: 0156, total loss=344.594943291
Epoch: 0157, total loss=344.597230066
Epoch: 0158, total loss=344.599682331
Epoch: 0159, total loss=344.601982625
Epoch: 0160, total loss=344.604454077
Epoch: 0161, total loss=344.606751037
Epoch: 0162, total loss=344.609147584
Epoch: 0163, total loss=344.611389366
Epoch: 0164, total loss=344.613845659
Epoch: 0165, total loss=344.616020591
Epoch: 0166, total loss=344.618320661
Epoch: 0167, total loss=344.620561997
Epoch: 0168, total loss=344.622801778
Epoch: 0169, total loss=344.625028922
Epoch: 0170, total loss=344.627400860
Epoch: 0171, total loss=344.629457572
Epoch: 0172, total loss=344.631473126
Epoch: 0173, total loss=344.633922616
Epoch: 0174, total loss=344.635971269
Epoch: 0175, total loss=344.638104674
Epoch: 0176, total loss=344.640216626
Epoch: 0177, total loss=344.642396941
Epoch: 0178, total loss=344.644255484
Epoch: 0179, total loss=344.646488231
Epoch: 0180, total loss=344.648470700
Epoch: 0181, total loss=344.650380419
Epoch: 0182, total loss=344.652470940
Epoch: 0183, total loss=344.654420350
Epoch: 0184, total loss=344.656385070
Epoch: 0185, total loss=344.658303362
Epoch: 0186, total loss=344.660223495
Epoch: 0187, total loss=344.662170963
Epoch: 0188, total loss=344.663969963
Epoch: 0189, total loss=344.665873676
Epoch: 0190, total loss=344.667657994
Epoch: 0191, total loss=344.669545869
Epoch: 0192, total loss=344.671246354
Epoch: 0193, total loss=344.673084837
Epoch: 0194, total loss=344.674759104
Epoch: 0195, total loss=344.676669396
Epoch: 0196, total loss=344.678335249
Epoch: 0197, total loss=344.680096914
Epoch: 0198, total loss=344.681685667
Epoch: 0199, total loss=344.683399036
Epoch: 0200, total loss=344.684959491
Epoch: 0201, total loss=344.686777129
Epoch: 0202, total loss=344.688348777
Epoch: 0203, total loss=344.689850317
Epoch: 0204, total loss=344.691466848
Epoch: 0205, total loss=344.692923116
Epoch: 0206, total loss=344.694530306
Epoch: 0207, total loss=344.696093414
Epoch: 0208, total loss=344.697719426
Epoch: 0209, total loss=344.698977387
Epoch: 0210, total loss=344.700443663
Epoch: 0211, total loss=344.701919074
Epoch: 0212, total loss=344.703406224
Epoch: 0213, total loss=344.704836698
Epoch: 0214, total loss=344.706129619
Epoch: 0215, total loss=344.707482434
Epoch: 0216, total loss=344.708959806
Epoch: 0217, total loss=344.710283162
Epoch: 0218, total loss=344.711606734
Epoch: 0219, total loss=344.712976503
Epoch: 0220, total loss=344.714136558
Epoch: 0221, total loss=344.715498271
Epoch: 0222, total loss=344.716810425
Epoch: 0223, total loss=344.717919824
Epoch: 0224, total loss=344.719192828
Epoch: 0225, total loss=344.720456437
Epoch: 0226, total loss=344.721726398
Epoch: 0227, total loss=344.722758737
Epoch: 0228, total loss=344.723953955
Epoch: 0229, total loss=344.725158928
Epoch: 0230, total loss=344.726027145
Epoch: 0231, total loss=344.727422578
Epoch: 0232, total loss=344.728455831
Epoch: 0233, total loss=344.729484540
Epoch: 0234, total loss=344.730696928
Epoch: 0235, total loss=344.731568906
Epoch: 0236, total loss=344.732745079
Epoch: 0237, total loss=344.733779195
Epoch: 0238, total loss=344.734846026
Epoch: 0239, total loss=344.735799723
Epoch: 0240, total loss=344.736678162
Epoch: 0241, total loss=344.737686713
Epoch: 0242, total loss=344.738614320
Epoch: 0243, total loss=344.739637943
Epoch: 0244, total loss=344.740552544
Epoch: 0245, total loss=344.741469918
Epoch: 0246, total loss=344.742432971
Epoch: 0247, total loss=344.743313771
Epoch: 0248, total loss=344.744197413
Epoch: 0249, total loss=344.745050630
Epoch: 0250, total loss=344.745934587
Epoch: 0251, total loss=344.746646335
Epoch: 0252, total loss=344.747609960
Epoch: 0253, total loss=344.748346270
Epoch: 0254, total loss=344.749256735
Epoch: 0255, total loss=344.750048325
Epoch: 0256, total loss=344.750853266
Epoch: 0257, total loss=344.751521764
Epoch: 0258, total loss=344.752401822
Epoch: 0259, total loss=344.753156053
Epoch: 0260, total loss=344.753896269
Epoch: 0261, total loss=344.754756612
Epoch: 0262, total loss=344.755379137
Epoch: 0263, total loss=344.756041465
Epoch: 0264, total loss=344.756716930
Epoch: 0265, total loss=344.757554952
Epoch: 0266, total loss=344.758029405
Epoch: 0267, total loss=344.758747140
Epoch: 0268, total loss=344.759471786
Epoch: 0269, total loss=344.760089554
Epoch: 0270, total loss=344.760815955
Epoch: 0271, total loss=344.761309733
Epoch: 0272, total loss=344.762014099
Epoch: 0273, total loss=344.762711936
Epoch: 0274, total loss=344.763246054
Epoch: 0275, total loss=344.763951013
Epoch: 0276, total loss=344.764469752
Epoch: 0277, total loss=344.765111495
Epoch: 0278, total loss=344.765558633
Epoch: 0279, total loss=344.766141303
Epoch: 0280, total loss=344.766842760
Epoch: 0281, total loss=344.767293007
Epoch: 0282, total loss=344.767756880
Epoch: 0283, total loss=344.768334480
Epoch: 0284, total loss=344.768862502
Epoch: 0285, total loss=344.769400297
Epoch: 0286, total loss=344.769780472
Epoch: 0287, total loss=344.770308272
Epoch: 0288, total loss=344.770956363
Epoch: 0289, total loss=344.771478710
Epoch: 0290, total loss=344.771879568
Epoch: 0291, total loss=344.772343092
Epoch: 0292, total loss=344.772872703
Epoch: 0293, total loss=344.773279164
Epoch: 0294, total loss=344.773690573
Epoch: 0295, total loss=344.774205158
Epoch: 0296, total loss=344.774763084
Epoch: 0297, total loss=344.774983885
Epoch: 0298, total loss=344.775492739
Epoch: 0299, total loss=344.775976786
Epoch: 0300, total loss=344.776284705
Epoch: 0301, total loss=344.776727325
Epoch: 0302, total loss=344.777153248
Epoch: 0303, total loss=344.777599962
Epoch: 0304, total loss=344.778012626
Epoch: 0305, total loss=344.778391708
Epoch: 0306, total loss=344.778744749
Epoch: 0307, total loss=344.779157798
Epoch: 0308, total loss=344.779415882
Epoch: 0309, total loss=344.779760242
Epoch: 0310, total loss=344.780301372
Epoch: 0311, total loss=344.780566747
Epoch: 0312, total loss=344.780780159
Epoch: 0313, total loss=344.781152271
Epoch: 0314, total loss=344.781567551
Epoch: 0315, total loss=344.781955882
Epoch: 0316, total loss=344.782298973
Epoch: 0317, total loss=344.782563084
Epoch: 0318, total loss=344.782790449
Epoch: 0319, total loss=344.783111421
Epoch: 0320, total loss=344.783526221
Epoch: 0321, total loss=344.783790750
Epoch: 0322, total loss=344.784034789
Epoch: 0323, total loss=344.784396090
Epoch: 0324, total loss=344.784592988
Epoch: 0325, total loss=344.784973161
Epoch: 0326, total loss=344.785243509
Epoch: 0327, total loss=344.785585406
Epoch: 0328, total loss=344.785873044
Epoch: 0329, total loss=344.786057136
Epoch: 0330, total loss=344.786275216
Epoch: 0331, total loss=344.786676057
Epoch: 0332, total loss=344.786878014
Epoch: 0333, total loss=344.787089007
Epoch: 0334, total loss=344.787305563
Epoch: 0335, total loss=344.787607596
Epoch: 0336, total loss=344.787790935
Epoch: 0337, total loss=344.788074106
Epoch: 0338, total loss=344.788277750
Epoch: 0339, total loss=344.788575002
Epoch: 0340, total loss=344.788726995
Epoch: 0341, total loss=344.788898576
Epoch: 0342, total loss=344.789163731
Epoch: 0343, total loss=344.789320700
Epoch: 0344, total loss=344.789577840
Epoch: 0345, total loss=344.789821679
Epoch: 0346, total loss=344.790069818
Epoch: 0347, total loss=344.790189366
Epoch: 0348, total loss=344.790324566
Epoch: 0349, total loss=344.790578877
Epoch: 0350, total loss=344.790677768
Epoch: 0351, total loss=344.790968372
Epoch: 0352, total loss=344.791223870
Epoch: 0353, total loss=344.791368898
Epoch: 0354, total loss=344.791488510
Epoch: 0355, total loss=344.791763988
Epoch: 0356, total loss=344.791887852
Epoch: 0357, total loss=344.792086885
Epoch: 0358, total loss=344.792271876
Epoch: 0359, total loss=344.792436252
Epoch: 0360, total loss=344.792605583
Epoch: 0361, total loss=344.792703344
Epoch: 0362, total loss=344.792824416
Epoch: 0363, total loss=344.793050225
Epoch: 0364, total loss=344.793264607
Epoch: 0365, total loss=344.793444358
Epoch: 0366, total loss=344.793552111
Epoch: 0367, total loss=344.793747179
Epoch: 0368, total loss=344.793804545
Epoch: 0369, total loss=344.794041655
Epoch: 0370, total loss=344.794057487
Epoch: 0371, total loss=344.794272224
Epoch: 0372, total loss=344.794382088
Epoch: 0373, total loss=344.794520581
Epoch: 0374, total loss=344.794693597
Epoch: 0375, total loss=344.794852945
Epoch: 0376, total loss=344.795005586
Epoch: 0377, total loss=344.795142179
Epoch: 0378, total loss=344.795284456
Epoch: 0379, total loss=344.795383347
Epoch: 0380, total loss=344.795455629
Epoch: 0381, total loss=344.795604541
Epoch: 0382, total loss=344.795777477
Epoch: 0383, total loss=344.795881867
Epoch: 0384, total loss=344.795969904
Epoch: 0385, total loss=344.796045731
Epoch: 0386, total loss=344.796146819
Epoch: 0387, total loss=344.796302433
Epoch: 0388, total loss=344.796324963
Epoch: 0389, total loss=344.796343317
Epoch: 0390, total loss=344.796590765
Epoch: 0391, total loss=344.796632202
Epoch: 0392, total loss=344.796645818
Epoch: 0393, total loss=344.796914760
Epoch: 0394, total loss=344.797004426
Epoch: 0395, total loss=344.797021405
Epoch: 0396, total loss=344.797153486
Epoch: 0397, total loss=344.797247913
Epoch: 0398, total loss=344.797420771
Epoch: 0399, total loss=344.797469154
Epoch: 0400, total loss=344.797491175
Epoch: 0401, total loss=344.797572117
Epoch: 0402, total loss=344.797789766
Epoch: 0403, total loss=344.797730108
Epoch: 0404, total loss=344.797781004
Epoch: 0405, total loss=344.797922127
Epoch: 0406, total loss=344.798075603
Epoch: 0407, total loss=344.798131449
Epoch: 0408, total loss=344.798115756
Epoch: 0409, total loss=344.798234780
Epoch: 0410, total loss=344.798359436
Epoch: 0411, total loss=344.798363091
Epoch: 0412, total loss=344.798483786
Epoch: 0413, total loss=344.798525549
Epoch: 0414, total loss=344.798652636
Epoch: 0415, total loss=344.798674707
Epoch: 0416, total loss=344.798778940
Epoch: 0417, total loss=344.798853364
Epoch: 0418, total loss=344.798868490
Epoch: 0419, total loss=344.798937856
Epoch: 0420, total loss=344.799041370
Epoch: 0421, total loss=344.799099345
Epoch: 0422, total loss=344.799194588
Epoch: 0423, total loss=344.799202929
Epoch: 0424, total loss=344.799292762
Epoch: 0425, total loss=344.799244923
Epoch: 0426, total loss=344.799327977
Epoch: 0427, total loss=344.799372675
Epoch: 0428, total loss=344.799457961
Epoch: 0429, total loss=344.799489198
Epoch: 0430, total loss=344.799639749
Epoch: 0431, total loss=344.799702113
Epoch: 0432, total loss=344.799761109
Epoch: 0433, total loss=344.799847648
Epoch: 0434, total loss=344.799903676
Epoch: 0435, total loss=344.799923422
Epoch: 0436, total loss=344.799944327
Epoch: 0437, total loss=344.799967102
Epoch: 0438, total loss=344.800017772
Epoch: 0439, total loss=344.800066812
Epoch: 0440, total loss=344.800090765
Epoch: 0441, total loss=344.800139479
Epoch: 0442, total loss=344.800177870
Epoch: 0443, total loss=344.800291823
Epoch: 0444, total loss=344.800333457
Epoch: 0445, total loss=344.800351068
Epoch: 0446, total loss=344.800427718
Epoch: 0447, total loss=344.800437734
Epoch: 0448, total loss=344.800469834
Epoch: 0449, total loss=344.800541630
Epoch: 0450, total loss=344.800631672
Epoch: 0451, total loss=344.800671516
Epoch: 0452, total loss=344.800776761
Epoch: 0453, total loss=344.800807456
Epoch: 0454, total loss=344.800749326
Epoch: 0455, total loss=344.800792818
Epoch: 0456, total loss=344.800824776
Epoch: 0457, total loss=344.800849435
Epoch: 0458, total loss=344.800933049
Epoch: 0459, total loss=344.800898556
Epoch: 0460, total loss=344.800982568
Epoch: 0461, total loss=344.801032884
Epoch: 0462, total loss=344.801028624
Epoch: 0463, total loss=344.801031651
Epoch: 0464, total loss=344.801023277
Epoch: 0465, total loss=344.801149821
Epoch: 0466, total loss=344.801165135
Epoch: 0467, total loss=344.801213399
Epoch: 0468, total loss=344.801174382
Epoch: 0469, total loss=344.801209778
Epoch: 0470, total loss=344.801292597
Epoch: 0471, total loss=344.801247181
Epoch: 0472, total loss=344.801313687
Epoch: 0473, total loss=344.801311298
Epoch: 0474, total loss=344.801335522
Epoch: 0475, total loss=344.801396256
Epoch: 0476, total loss=344.801450556
Epoch: 0477, total loss=344.801487517
Epoch: 0478, total loss=344.801479184
Epoch: 0479, total loss=344.801464160
Epoch: 0480, total loss=344.801497417
Epoch: 0481, total loss=344.801588677
Epoch: 0482, total loss=344.801548893
Epoch: 0483, total loss=344.801521150
Epoch: 0484, total loss=344.801637657
Epoch: 0485, total loss=344.801599232
Epoch: 0486, total loss=344.801602177
Epoch: 0487, total loss=344.801659987
Epoch: 0488, total loss=344.801672416
Epoch: 0489, total loss=344.801685953
Epoch: 0490, total loss=344.801702979
Epoch: 0491, total loss=344.801750470
Epoch: 0492, total loss=344.801789066
Epoch: 0493, total loss=344.801803662
Epoch: 0494, total loss=344.801828721
Epoch: 0495, total loss=344.801826514
Epoch: 0496, total loss=344.801919691
Epoch: 0497, total loss=344.801897655
Epoch: 0498, total loss=344.801941082
Epoch: 0499, total loss=344.801938891
Epoch: 0500, total loss=344.801902088
Training complete!
Accuracy on test set: 0.804469287